#          /\
#         /  \
#        /    \
#       /      \    Config By Axell, BTW ❄
#      /   ,,   \
#     /   |  |   \
#    /_-''    ''-_\

windowrule {
   name = ark
   match:class = org.kde.ark
   float = yes
   center = yes
   size = 1093 661
}

windowrule {
   name = file-exists_ark
   match:class = org.kde.ark
   match:initial_title = .*File Already Exists.*
   float = yes
   center = yes
   size = 784 302
}

windowrule {
   name = extract_ark
   match:class = org.kde.ark
   match:initial_title = .*Extract.*
   float = yes
   center = yes
   size = 1241 826
}

windowrule {
   name = extract_prochess_ark
   match:class = org.kde.ark
   match:initial_title = .*Extracting.*
   float = yes
   center = yes
   size = 649 199
}

windowrule {
   name = loading_prochess_ark
   match:class = org.kde.ark
   match:initial_title = .*Loading archive.*
   float = yes
   center = yes
   size = 655 140
}