#          /\
#         /  \
#        /    \
#       /      \    Config By Axell, BTW ❄
#      /   ,,   \
#     /   |  |   \
#    /_-''    ''-_\

windowrule {
   name = dolphin
   match:class = org.kde.dolphin
   match:title = .*/.*
   min_size = 1060 548
}

windowrule {
   name = dolphin-Properties
   match:class = org.kde.dolphin
   match:initial_title = .*Properties for.*|*Choose Application.*
   float = yes
   center = yes
   size = window_w window_h
}

windowrule {
   name = copymove-dolphin
   match:class = org.kde.dolphin
   match:title = .*(Cop|Mov|Progress).*
   float = yes
   size = 580 210
   move = (monitor_w-window_w) monitor_h*0+35
}

windowrule {
   name = create-dolphin
   match:class = org.kde.dolphin
   match:title = .*(File Already Exists|Progress Dialog|Creating directory).*
   float = yes
   center = yes
   size = window_w window_h
}

windowrule {
   name = dolphin-file-exist
   match:class = org.kde.dolphin
   match:initial_title = .*File Already Exists.*
   float = yes
   center = yes
}