#          /\
#         /  \
#        /    \
#       /      \    Config By Axell, BTW ❄
#      /   ,,   \
#     /   |  |   \
#    /_-''    ''-_\

windowrule {
   name = flameshot
   match:class = flameshot
   #fullscreen = yes
   #fullscreen_state = 2
   float = yes
   size = monitor_w monitor_h
   move = 0 0
   opaque = yes
   rounding = 0
   border_size = 0
   no_blur = yes
   no_anim = yes
}

windowrule {
   name = flameshot-settings
   match:class = flameshot
   match:initial_title = .*(Настройки|Settings).*
   float = yes
   size = window_w window_h
   center = yes
   no_blur = no
   no_anim = no
   stay_focused = no
   pin = no
   border_size = 2
   rounding = 6
   opacity = 1
}

windowrule {
   name = flameshot-save
   match:class = flameshot
   match:title = .*(Сохранить|Save).*
   float = yes
   center = yes
   size = 1044 761
   no_blur = no
   no_anim = no
   stay_focused = no
   pin = no
   border_size = 2
   rounding = 6
   opacity = 0.8
}