#          /\
#         /  \
#        /    \
#       /      \    Config By Axell, BTW ❄
#      /   ,,   \
#     /   |  |   \
#    /_-''    ''-_\

windowrule {
   name = qBittorrent_all
   match:class = org.qbittorrent.qBittorrent
   match:title = .*
   float = yes
   center = yes
   size = 1360 731
}

windowrule {
   name = Delete_qBittorrent
   match:class = org.qbittorrent.qBittorrent
   match:title = .*(Удалить торрент|Remove|Delete).*
   float = yes
   center = yes
   size = 463 153
}

windowrule {
   name = Rename_qBittorrent
   match:class = org.qbittorrent.qBittorrent
   match:title = .*(Переименовать|Rename).*
   float = yes
   center = yes
   size = 222 105
}

windowrule {
   name = ViewNW_qBittorrent
   match:class = org.qbittorrent.qBittorrent
   match:title = .*(Просмотр не удался).*
   float = yes
   center = yes
   size = 500 98
}

windowrule {
   name = qBittorrent
   match:class = org.qbittorrent.qBittorrent
   match:title = .*(qBittorrent).*
   tile = yes
}