#          /\
#         /  \
#        /    \
#       /      \    Config By Axell, BTW ❄
#      /   ,,   \
#     /   |  |   \
#    /_-''    ''-_\

windowrule {
   name = steam
   match:class = steam
   match:initial_title = Steam
   tile = yes
   min_size = 964 675
}

windowrule {
   name = steam-dropwindow
   match:class = steam
   match:title = negative:Steam|()
   float = yes
   center = yes
   size = 920 571
   stay_focused = no
}

windowrule {
   name = steam-context-menu
   match:class = steam
   match:initial_title = ()
   float = yes
   stay_focused = no
   no_blur = yes
}

windowrule {
   name = steam-settings
   match:class = steam
   match:title = .*(Настройки|.*Settings).*
   float = yes
   center = yes
   size = 885 686
   stay_focused = no
}

windowrule {
   name = steam-friends
   match:class = steam
   match:title = .*(Список друзей|.*Friends List).*
   float = yes
   center = yes
   size = 925 591
   stay_focused = no
}

windowrule {
   name = steam-notification
   match:class = steam
   match:initial_title = .*notif.*
   float = yes
   center = no
   no_focus = yes
   no_blur = yes
}

windowrule {
   name = steam-dialog
   match:class = steam
   match:initial_title = .*(окно|Dialog).*
   float = yes
   center = yes
   size = window_w window_h
   stay_focused = no
}

windowrule {
   name = steam-about
   match:class = steam
   match:initial_title = .*(О Steam|About steam).*
   float = yes
   center = yes
   size = window_w window_h
   stay_focused = no
}

windowrule {
   name = steam-add-games
   match:class = steam
   match:initial_title = .*(Добавить стороннюю игру).*
   float = yes
   center = yes
   size = 900 790
   stay_focused = no
}

windowrule {
   name = steam-games
   match:class = .*steam_app.*
   float = yes
   tile = no
   center = yes
   no_blur = true
   opaque = yes
   stay_focused = no
}

windowrule {
   name = steam-games_menu
   match:class = .*steam_app.*
   match:initial_title = ()
   float = yes
   center = yes
   stay_focused = no
}

windowrule {
   name = steam-launch
   match:class = steam
   match:initial_title = .*(Запуск...|Launch...).*
   float = yes
   center = yes
   size = window_w window_h
   stay_focused = no
}

windowrule {
   name = steam-shutdown
   match:class = steam
   match:initial_title = .*(Завершение работы|Shutdown).*
   float = yes
   center = yes
   size = window_w window_h
   stay_focused = no
}

windowrule {
   name = steam-start
   match:class = steam
   match:initial_title = .*(Войти|Sign).*
   float = yes
   center = yes
   size = window_w window_h
   stay_focused = no
}