#          /\
#         /  \
#        /    \
#       /      \    Config By Axell, BTW ❄
#      /   ,,   \
#     /   |  |   \
#    /_-''    ''-_\

submap = passthrough
bind = SUPER, F, fullscreen, 0
bind = SUPER, F, submap, reset
submap = reset