#          /\
#         /  \
#        /    \
#       /      \    Config By Axell, BTW ❄
#      /   ,,   \
#     /   |  |   \
#    /_-''    ''-_\

windowrule {
   name = notile-class
   match:class = (?i).*(file_progress|confirm|dialog|download|notification|error|splash|org.kde.kdialog|wizard|assistant|auth|permission).*
   float = yes
   center = yes
}

windowrule {
   name = notile-title
   match:title = (?i).*(Open Files|Save File|Choose Files|Please choose a file).*
   float = yes
   center = yes
   size = window_w window_h
}