#          /\
#         /  \
#        /    \
#       /      \    Config By Axell, BTW ❄
#      /   ,,   \
#     /   |  |   \
#    /_-''    ''-_\

# █▀▀ ▀ ▀▃▀ █▔▔
# █▀  █ ▅▀▅ ▂▂█

windowrule {
   name = windows_size
   match:class = .*
   size = window_w window_h
   persistent_size = yes
}

windowrule {
   name = xwayland-video-bridge-fixes
   match:class = xwaylandvideobridge
   no_initial_focus = true
   no_focus = true
   no_anim = true
   no_blur = true
   max_size = 1 1
   opacity = 0.0
}