#          /\
#         /  \
#        /    \
#       /      \    Config By Axell, BTW ❄
#      /   ,,   \
#     /   |  |   \
#    /_-''    ''-_\

source = ~/.config/hypr/custom/vmware-input-fix.conf
source = ~/.config/hypr/custom/qbittorent-tile-fix.conf
source = ~/.config/hypr/custom/ark-tile-fix.conf
source = ~/.config/hypr/custom/steam-tile-fix.conf
source = ~/.config/hypr/custom/dolphin-tile.fix.conf
source = ~/.config/hypr/custom/flameshot-fix.conf
source = ~/.config/hypr/custom/windowfix.conf